name: Build

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-2022
    
    strategy:
      matrix:
        configuration: [Release]
        platform: [x64]

    steps:    
    - run: Get-PSDrive

    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{ matrix.configuration }} /p:Platform=${{ matrix.platform }} ShaderGlass.sln

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: 'ShaderGlass_${{ matrix.platform }}_${{ matrix.configuration }}'
        path: '.\${{ matrix.platform }}\${{ matrix.configuration }}\ShaderGlass.exe'
        overwrite: true
